#!/usr/bin/env python3
"""
Generate a stress-test docker-compose.yml for the Weather Station Simulator.

This script creates a docker-compose.stress.yml file with:
- 1 server (TCP listener)
- 1 web dashboard
- N weather station clients (configurable, default 50)

Each station client is configured with:
- Unique WEATHER_STATION_ID (e.g., STRESS-001, STRESS-002, ...)
- Fast interval: WEATHER_STATION_BATCH_INTERVAL=1 second
- Larger batches: WEATHER_STATION_BATCH_MIN=1, WEATHER_STATION_BATCH_MAX=5
- Timeout: 5.0 seconds
- Retries: 3

Usage:
    python scripts/gen_stress_compose.py [--stations N]

Examples:
    python scripts/gen_stress_compose.py                # generates 50 stations
    python scripts/gen_stress_compose.py --stations 100 # generates 100 stations
    python scripts/gen_stress_compose.py --stations 25  # generates 25 stations

The output file is: docker-compose.stress.yml
Run with:
    docker compose -f docker-compose.stress.yml up --build
Clean up with:
    docker compose -f docker-compose.stress.yml down -v
"""

import argparse
import sys
from pathlib import Path


def generate_station_yaml(station_id: int) -> str:
    """Generate YAML for a single weather station service."""
    station_num = f"{station_id:03d}"
    station_name = f"STRESS-{station_num}"
    service_key = f"station-stress-{station_num}"
    
    return f"""
  {service_key}:
    build:
      context: ./station_client
      dockerfile: Dockerfile
    container_name: weather-stress-station-{station_num}
    environment:
      - WEATHER_STATION_HOST=server
      - WEATHER_STATION_PORT=12345
      - WEATHER_STATION_ID={station_name}
      - WEATHER_STATION_BATCH_MIN=1
      - WEATHER_STATION_BATCH_MAX=5
      - WEATHER_STATION_BATCH_INTERVAL=1
      - WEATHER_STATION_TIMEOUT=5.0
      - WEATHER_STATION_MAX_RETRIES=3
      - PYTHONUNBUFFERED=1
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - weather-network"""


def generate_compose_yaml(num_stations: int) -> str:
    """Generate the complete docker-compose.yml content."""
    stations_yaml = "".join(generate_station_yaml(i) for i in range(1, num_stations + 1))
    
    yaml_content = f"""version: '3.8'

# ============================================================================
# STRESS TEST DOCKER COMPOSE FOR WEATHER STATION SIMULATOR
# ============================================================================
# This compose file is auto-generated by scripts/gen_stress_compose.py
# It runs:
#   - 1 TCP server (port 12345)
#   - 1 web dashboard (port 8000)
#   - {num_stations} weather station clients with stress parameters:
#       - Fast interval: 1 second between batches
#       - Larger batches: 1-5 readings per batch
#       - Unique IDs: STRESS-001 to STRESS-{num_stations:03d}
#
# USAGE:
#   Generate (with custom count):
#     python scripts/gen_stress_compose.py --stations 100
#
#   Run:
#     docker compose -f docker-compose.stress.yml up --build
#
#   Clean up:
#     docker compose -f docker-compose.stress.yml down -v
# ============================================================================

services:

  # TCP Server - receives weather data and stores in SQLite
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: weather-server
    ports:
      - "12345:12345"
    volumes:
      # Persistent storage for SQLite database
      - weather-data:/app/data
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=12345
      - DB_PATH=/app/data/weather.db
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - weather-network
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.connect(('localhost',12345)); s.close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Web Dashboard - Flask UI for viewing data
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: weather-web
    ports:
      - "8000:8000"
    volumes:
      # Share the same database volume (read-only for web)
      - weather-data:/app/data:ro
    environment:
      - WEATHER_DB_PATH=/app/data/weather.db
      - WEB_HOST=0.0.0.0
      - WEB_PORT=8000
      - PYTHONUNBUFFERED=1
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - weather-network

  # ========================================================================
  # STRESS TEST WEATHER STATION CLIENTS
  # ========================================================================
  # {num_stations} weather station clients configured for load testing
  # Each sends at 1-second intervals with 1-5 readings per batch
{stations_yaml}

volumes:
  # Named volume for persistent SQLite database
  weather-data:
    driver: local

networks:
  weather-network:
    driver: bridge
"""
    return yaml_content


def main():
    parser = argparse.ArgumentParser(
        description="Generate a stress-test docker-compose.yml for Weather Station Simulator"
    )
    parser.add_argument(
        "--stations",
        type=int,
        default=50,
        help="Number of weather station clients to create (default: 50)"
    )
    
    args = parser.parse_args()
    
    if args.stations < 1:
        print("Error: --stations must be at least 1", file=sys.stderr)
        sys.exit(1)
    
    if args.stations > 500:
        print("Warning: Creating more than 500 stations may cause performance issues", file=sys.stderr)
    
    # Get the repo root (parent of scripts directory)
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent
    output_file = repo_root / "docker-compose.stress.yml"
    
    print(f"Generating docker-compose.stress.yml with {args.stations} weather station clients...")
    
    yaml_content = generate_compose_yaml(args.stations)
    
    # Write to file
    with open(output_file, "w") as f:
        f.write(yaml_content)
    
    print(f"✓ Generated: {output_file}")
    print(f"\nTo run the stress test:")
    print(f"  docker compose -f docker-compose.stress.yml up --build")
    print(f"\nTo clean up:")
    print(f"  docker compose -f docker-compose.stress.yml down -v")


if __name__ == "__main__":
    main()
